spring:
  profiles:
    active: "local"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://rds-20221017.codikrzkcgf4.ap-northeast-2.rds.amazonaws.com/auction?useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: kimhb09@ajou.ac.kr
    password: rlagusqls1!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

cloud:
  aws:
    credentials:
      accessKey: secret
      secretKey: secret
    s3:
      bucket: s3-20221018
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8080