spring:
  profiles:
    active: "local"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: rlagusqls1!
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      generate-ddl: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update