spring:
  profiles:
    active: "local"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    # local DB
    # url: jdbc:mysql://127.0.0.1:3306/sys?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    # username: root
    # password: rlagusqls1!
    url: jdbc:mysql://rds-20221017.codikrzkcgf4.ap-northeast-2.rds.amazonaws.com/sys?useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      generate-ddl: true
      open-in-view: false
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimhb09@ajou.ac.kr
    password: rlagusqls1!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
